model_name: stacking_classifier
target: EquipoGanador
features:
- equipo_primera_sangre
- asesinatos_dif
- asistencias_diforo_dif
- nivel_dif
- minions_dif
- torretas_dif
- dragones_dif
- heraldos_dif
estimators:
- name: lr
  type: LogisticRegression
  params:
    max_iter: 1000
- name: svc
  type: SVC
  params:
    C: 100
    gamma: 0.001
    kernel: rbf
    probability: true
- name: xgb
  type: XGBClassifier
  params:
    colsample_bytree: 0.7
    learning_rate: 0.03
    max_depth: 3
    n_estimators: 150
    subsample: 0.8
final_estimator:
  type: LogisticRegression
  params:
    max_iter: 1000
cv: 5
n_jobs: -1
decision_thresholds:
  surrender_alert: 0.2
  safe_win: 0.7
